server:
  retention: 1h
  remoteWrite:
        - url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-57d7d844-12a4-4daf-96dd-636c4d8d9f61/api/v1/remote_write
          sigv4:
            region: us-east-1
          queue_config:
            max_samples_per_send: 1000
            max_shards: 200
            capacity: 2500
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  nodeSelector:
    kubernetes.io/os: linux

  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 20Gi
    storageClass: gp2

serviceAccounts:
    server:
        name: "amp-iamproxy-ingest-service-account"
        annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::219596081057:role/amp-iamproxy-ingest-role"

alertmanager:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux

kube-state-metrics:
  enabled: true
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

pushgateway:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux

nodeExporter:
  nodeSelector:
    kubernetes.io/os: linux

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi