anchors:
  configure-aws-access: &configure-aws-access
    run:
      name: Configure AWS access
      command: |
        mkdir -p ~/.aws
        file=~/.aws/credentials
        echo "[default]" > $file
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> $file
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> $file

  deploy-infra: &deploy-infra
    run:
      name: Deploy terraform platform infra
      command: |
        bash ./terraform_exec.sh 1

  destroy-infra: &destroy-infra
    run:
      name: Destroy Kuberntes Apps
      command: |
        bash ./terraform_exec.sh 2

  install-dependencies: &install-dependencies
    run:
      name: Install terraform
      command: |
        bash ./install_terraform.sh


jobs:
  deployInfra:
    #executor: machine
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - *install-dependencies
      - *configure-aws-access
      - *deploy-infra

  destroyInfra:
    #executor: machine
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - *install-dependencies
      - *configure-aws-access
      - *destroy-infra

workflows:
  version: 2
  devDeploy:
    jobs:
      - deployInfra:
          context: ISENGARD-DEV
          filters:
            branches:
              only:
                - dev
                - /^eks\-.*/
                - /^XDP\-.*/
  devDestroy:
    jobs:
      - destroyInfra:
          context: ISENGARD-DEV
          filters:
            branches:
              only:
                - dev-destroy

  stageDeploy:
    jobs:
      - deployInfra:
          context: ISENGARD-STAGE
          filters:
            branches:
              only:
                - main
  stageDestroy:
    jobs:
      - destroyInfra:
          context: ISENGARD-STAGE
          filters:
            branches:
              only:
                - main-destroy

  prodDeploy:
    jobs:
      - approve-deploy:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
      - deployInfra:
          context: ISENGARD-PROD
          filters:
            tags:
              only:
                - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
            branches:
              ignore: /.*/
          requires:
            - approve-deploy
